import './globals.css';
import Providers from '../utils/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-w-0 w-full max-w-screen-xl mx-auto">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
