import Providers from '../utils/providers';

export const metadata = {
  title: 'Fullstack Challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="min-w-0 w-full max-w-screen-xl mx-auto">
      <Providers>
        {children}
      </Providers>
    </div>
  );
}